# Generated by Django 4.1 on 2022-09-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeleSettings',
            new_name='TeleSetting',
        ),
    ]
